// <auto-generated />
using System;
using B_Commerce.LogService.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace B_Commerce.LogService.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191203201103_Thirth Migration")]
    partial class ThirthMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("B_Commerce.LogService.DomainClasses.LogInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogInfoMessage")
                        .IsRequired()
                        .HasColumnName("LogInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deleteDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deleteUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("insertDateTime")
                        .HasColumnName("LogInsertDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("insertUserId")
                        .HasColumnType("int");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("ProjectID");

                    b.ToTable("LogInfos");
                });

            modelBuilder.Entity("B_Commerce.LogService.DomainClasses.ProjectInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("deleteDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deleteUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("insertDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("insertUserId")
                        .HasColumnType("int");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("ProjectInfos");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Password = "admin",
                            ProjectCode = "code",
                            insertDateTime = new DateTime(2019, 12, 3, 23, 11, 2, 643, DateTimeKind.Local).AddTicks(6598),
                            isDeleted = false
                        });
                });

            modelBuilder.Entity("B_Commerce.LogService.DomainClasses.ProjectOwner", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("IsRequestEmail")
                        .HasColumnType("bit");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deleteDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deleteUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("insertDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("insertUserId")
                        .HasColumnType("int");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("ID")
                        .HasName("OwnerID");

                    b.HasIndex("ProjectID");

                    b.ToTable("ProjectOwners");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Email = "hacimu@gmail.com",
                            IsRequestEmail = true,
                            ProjectID = 1,
                            insertDateTime = new DateTime(2019, 12, 3, 23, 11, 2, 654, DateTimeKind.Local).AddTicks(9212),
                            isDeleted = false
                        });
                });

            modelBuilder.Entity("B_Commerce.LogService.DomainClasses.LogInfo", b =>
                {
                    b.HasOne("B_Commerce.LogService.DomainClasses.ProjectInfo", "ProjectInfo")
                        .WithMany("LogInfos")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("B_Commerce.LogService.DomainClasses.ProjectOwner", b =>
                {
                    b.HasOne("B_Commerce.LogService.DomainClasses.ProjectInfo", "ProjectInfo")
                        .WithMany("ProjectOwners")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
